bastion_members = ["user:suryastef@gmail.com"]
project_id      = "sandbox-suryastef"
cluster_name    = "ss-cluster"
network_name    = "ss-cluster-network"
subnet_name     = "ss-cluster-subnet"
pool_name       = "ss-cluster-pool"
machine_type    = "n2-standard-2"
region          = "asia-southeast2"
zones           = ["asia-southeast2-a", "asia-southeast2-b", "asia-southeast2-c"]
