name: Terraform fmt and validate
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

env:
  exclude-dir-param: "-path './**/test/**' -o -path './**/modules/**'"

jobs:
  tf-fmt-validate:
    name: Terraform fmt and validate
    runs-on: ubuntu-latest
    steps:

    - name: Git Checkout bfi-terraform
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: >-
        for i in $(find . -type d \( ${{env.exclude-dir-param}} \) -prune -o -name '*.tf' -printf '%h\n' | sort | uniq);
        do 
            terraform -chdir=$i fmt;
        done

    - name: Debug
      run: echo running on branch ${{ github.head_ref || github.ref_name }} 

    - name: Update files on GitHub
      uses: test-room-7/action-update-file@v1.6.0
      with:
          branch: ${{ github.head_ref || github.ref_name }} 
          file-path: '**/*.tf'
          commit-msg: 'chore : terraform fmt'
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform init & validate
      id: validate
      run: >-
        for i in $(find . -type d \( ${{env.exclude-dir-param}} \) -prune -o -name '*.tf' -printf '%h\n' | sort | uniq);
        do 
            terraform -chdir=$i init -backend=false;
            terraform -chdir=$i validate -no-color;
        done

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.4.0
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform 